// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtygvomdmdwmlrnqaqbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0eWd2b21kbWR3bWxybnFhcWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MDk4NDUsImV4cCI6MjA1NzA4NTg0NX0.mAX3WnPwTx5-htDPiotQXKynH0O0IX6Owp-0L5YZ3Sk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);